### ISSUE TITLE
Fractions of bolus insulin units rounded up; basal mixed up with bolus

### ISSUE THREAD

**Issue by steve8x8** [zreptil/nightscout-reporter#27]
Seen with 1.3.4: When I use a bolus of 2.5 U, the "icicle" shows the correct length but the label says "3". This rounded value is also used for the daily total. (which btw doesn't identify the basal as such - boluses are reported to NS as eventType=Bolus while basals are eventType=Note - but summarizes all insulin!=none into the bolus sum)
My basal insulin pen doesn't allow fractions, but the issue may be more general.

**Comment by zreptil** [comment]
If your insulin pen doesn't allow fractions, why do you input a bolus of 2.5 U? Maybe this issue is solved in the beta at https://nightscout-reporter.zreptil.de/beta. Please take a look there. If this issue still persists there, please send me a link to your data, so that I can try to find the problem.

**Comment by steve8x8** [comment]
1.3.6ßf still has the problem.
Data: zehn.be port 6089, 2019-11-28 had 4U morning basal, 2.5U breakfast bolus, 3U night basal. 

The attached image shows another day, same issue: 3U basal, 2.5U bolus, different lengths, identical label.
![Screen Shot 2019-12-09 at 17 02 05](https://user-images.githubusercontent.com/11962538/70452109-dcd41000-1aa6-11ea-8da8-763e307f401c.png)

Its' the basal pen that doesn't allow fractions...

**Comment by zreptil** [comment]
To see the data, I need the URL you entered in the settings of Nightscout Reporter. Also, I am a little confused: do you use a pump or a pen? You tell me your pen doesn't allow fractions, but you enter fractions. Where do you get this fractions from?

**Comment by steve8x8** [comment]
Okay, it looks like I've got to invite visitors by writing the full URL: http s://ns.10be.de:6089/
I've got two pens: a "normal" one for basal, a kids' pen for boluses. The latter (and only that) allows half units.
Insulin records, meals, and exercises are recorded separately and uploaded once per week, CGM is managed by xDrip.

**Comment by steve8x8** [comment]
Checked with 1.3.6 released version today, and found
- pen basal interpreted as bolus (there's no pump, no basal profile that could be summed up)
- pen bolus rounded to integer units (this is a pen that can provide half units)
Nightscout has "eventType":"Bolus" insulin records and "eventType":"note","notes":"Basal" ones; NSRep appears to only sum the "insulin":number values? (In the graphs, as stated before, the lengths of the "icicles" are correct, a 2.5U bolus is shorter than a 3U basal, but both get a "3U" label and their sum is 6.0U.) Still the same NS instance as before

**Comment by zreptil** [comment]
Is this still an issue?

**Comment by steve8x8** [comment]
It is, even with /beta/. I'll send the API details

**Comment by zreptil** [comment]
Thanks for the data. I think, this will be fixed in 1.3.9.

**Comment by zreptil** [comment]
I uploaded 1.3.9 to beta. There you have an option in the daily graphic to disable the rounding of the insulin to the profile.

**Comment by steve8x8** [comment]
Thanks, I'll check when home.
The question remains, why round at all? I suppose the sums are correct?

**Comment by zreptil** [comment]
The answer is as follows: one who uses profiles has a special precision in insulindelivery. It my be 0.5 ie or 0.1 ie or even 0.01 ie. So, Nightscout Reporter takes the highest precision it finds in the profile and uses this to display every insulin unit. In my eyes, it doesn't make sense to show higher precision than the pump can deliver. It would lead to confusion (at least, i would be confused, this is fair enough for me to include the calculations in this way ^^)

But as i know now, not every user has a profile or enters the values in the profile with the correct precision. So i included the option to omit the rounding. I hope this helps. If this is not enough, i consider an option where the precision can be selected. But up to now i think it is easier for the user if it is done automatically.

Ease of use is still one of my highest targets in this project.

**Comment by steve8x8** [comment]
"Insulin auf maximale Stellen im Profil runden" *not ticked* does the trick indeed. (Is it me or is the wording a bit confusing?)

I still notice that Basal and Bolus injections are properly labelled but all summing goes into the Total Bolus value, i.e., Basal would just represent the sum of the daily basal profile, not individual injections. This may be intended...

**Comment by zreptil** [comment]
Maybe the wording is confusing, because it is german. If you switch to english it will read "Round insulin to maximum precision in profile". It says, what is done, when the option is ticked. You need it to be not ticked, since you don't want the rounding. I think the wording is correct. If anybody has a better idea, just let me know.

The summing is inteded. If you give Insulin due to a basalrate, it is calculated as basal, if you give it as injection it is bolus. With pens you normally have a bolus pen and a basal pen. Up to now these two are not handled differently. Bolus doesn't mean, that it has something to do with eating. It just is a insulin dose that is given to adjust the values. This may be due to eating or because you need to adjust the value to get to the target area. Both injections are counted as bolus.
