### ISSUE TITLE
Feature / Bug - Base Rate 2,4U

### ISSUE THREAD

**Issue by KevinDenys** [zreptil/nightscout-reporter#57]
I never fill in my insuline unites but this bar always shows 2.4Units.
![image](https://user-images.githubusercontent.com/17174443/134423497-1df9e10f-b7c5-4143-bf96-c2623c704aff.png)
If it's intended could you explain it and give us the option to hide the graphs.

**Comment by KevinDenys** [comment]
Same here
![image](https://user-images.githubusercontent.com/17174443/134424032-e0b49372-bea3-49fb-b634-b4940d4bb47b.png)

**Comment by zreptil** [comment]
This is intended, since it is the graph for the basalrate. It shows the insulin that is entered in the profile in the nightscout site. If you don't want to see it, just deactivate the options daily basalrate and profile basalrate in the settings for the form.

But I am curious: if you never fill in your insulin units: why do you use nightscout or nightscout reporter?

**Comment by KevinDenys** [comment]
I use it to store my glucose values and the reporter because I need to show my glucose values to my doctor 😅

**Comment by KevinDenys** [comment]
Also xdrip4ios does not support filling in basal rates

**Comment by zreptil** [comment]
Ah, ok, then it is just a diary. If you need to remove additional outputs from the forms just tell me. I can add options to make things more flexible :)

**Comment by KevinDenys** [comment]
Just tested it, I can indeed uncheck the insuline information. Perfect! Closing this ticket 👍
