### ISSUE TITLE
Integrate it with the official cgm-remote-monitor

### ISSUE THREAD

**Issue by fnandot** [zreptil/nightscout-reporter#69]
Awesome report tool! What do you think about integrate it on the official Nightscout repo? That way would be more accessible for everyone.

**Comment by zreptil** [comment]
I thought about it, but since nightscout reporter is already very easy accessible for everybody who has an internet connection, it makes not really sense to integrate it with nightscout. It has no server components and runs completely in the browser of the user. The only server access (up to now, changes with the next version) is a small php script that is needed to run pdfmake on the server, since it didn't integrate with angular dart.

The next version will be a complete rewrite in angular and this version will need no server component at all. So it is very easy to access it from all over the world without installing anything.
