### ISSUE TITLE
Compiled version link is not working anymore

### ISSUE THREAD

**Issue by quietwalker-libre** [zreptil/nightscout-reporter#75]
Hello,
I was trying to download the compiled version of nighscout-reporter from the link in the README page, but it looks like it's broken atm.

The link, specifically, is this: https://nightscout-reporter.zreptil.de/nightscout-reporter_local.zip

when I click on it, the browser redirect me to https://nightrep.zreptil.de/ instead of letting me download the zip archive. 
Could you please check? 

Thanks for your amazing work!

**Comment by zreptil** [comment]
Hi quietwalker,

you are in an outdated repositore :) The current repository for nightscout reporter is at https://github.com/zreptil/nightscout-reporter-angular. I had to switch to angular away from dart, since google gave up on dart and further development made no sense with the incompatible dart- and material-framework. The url https://nightscout-reporter.zreptil.de is outdated since about a year. Just go to the repository mentioned above and you have the current version of nightscout reporter :)
